#Based on code originally written by Alex Sheu
#Can view five brains side by side
#Modified by Austin Kao

customLayout = ("<layout type=\"horizontal\">"
  " <item>"
  "  <layout type=\"vertical\">"
  "	  <item>"
  " 	<view class=\"vtkMRMLViewNode\" singletontag=\"1\" verticalStretch=\"0\">"
  "    		<property name=\"viewlabel\" action=\"default\">1</property>"
  "  	</view>"
  "   </item>"
  "   <item>"
  "    	<view class=\"vtkMRMLSliceNode\" singletontag=\"Red\">"
  "      <property name=\"orientation\" action=\"default\">Axial</property>"
  "      <property name=\"viewlabel\" action=\"default\">R</property>"
  "      <property name=\"viewcolor\" action=\"default\">#f9a99f</property>"
  "   	</view>"
  "   </item>"
  "  </layout>"
  " </item>"
  " <item>"
  "  <layout type=\"vertical\">"
  "	  <item>"
  " 	<view class=\"vtkMRMLViewNode\" singletontag=\"2\" verticalStretch=\"0\">"
  "    	 <property name=\"viewlabel\" action=\"default\">2</property>"
#  "      <property name=\"viewgroup\" action=\"default\">1</property>"
  "  	</view>"
  "   </item>"
  "   <item>"
  "    <view class=\"vtkMRMLSliceNode\" singletontag=\"Yellow\">"
  "     <property name=\"orientation\" action=\"default\">Axial</property>"
  "     <property name=\"viewlabel\" action=\"default\">Y</property>"
  "     <property name=\"viewcolor\" action=\"default\">#EDD54C</property>"
#  "     <property name=\"viewgroup\" action=\"default\">1</property>"
  "    </view>"
  "   </item>"
  "  </layout>"
  " </item>"
  " <item>"
  "  <layout type=\"vertical\">"
  "	  <item>"
  " 	<view class=\"vtkMRMLViewNode\" singletontag=\"3\" verticalStretch=\"0\">"
  "    	 <property name=\"viewlabel\" action=\"default\">3</property>"
#  "      <property name=\"viewgroup\" action=\"default\">1</property>"
  "  	</view>"
  "   </item>"
  "   <item>"
  "    <view class=\"vtkMRMLSliceNode\" singletontag=\"Green\">"
  "     <property name=\"orientation\" action=\"default\">Axial</property>"
  "     <property name=\"viewlabel\" action=\"default\">G</property>"
  "     <property name=\"viewcolor\" action=\"default\">#6EB04B</property>"
#  "     <property name=\"viewgroup\" action=\"default\">1</property>"
  "    </view>"
  "   </item>"
  "  </layout>"
  " </item>"
  " <item>"
  "  <layout type=\"vertical\">"
  "	  <item>"
  " 	<view class=\"vtkMRMLViewNode\" singletontag=\"4\" verticalStretch=\"0\">"
  "    	 <property name=\"viewlabel\" action=\"default\">4</property>"
#  "      <property name=\"viewgroup\" action=\"default\">1</property>"
  "  	</view>"
  "   </item>"
  "   <item>"
  "    <view class=\"vtkMRMLSliceNode\" singletontag=\"Red+\">"
  "     <property name=\"orientation\" action=\"default\">Axial</property>"
  "     <property name=\"viewlabel\" action=\"default\">R+</property>"
  "     <property name=\"viewcolor\" action=\"default\">#f9a99f</property>"
#  "     <property name=\"viewgroup\" action=\"default\">1</property>"
  "    </view>"
  "   </item>"
  "  </layout>"
  " </item>"
  " <item>"
  "  <layout type=\"vertical\">"
  "	  <item>"
  " 	<view class=\"vtkMRMLViewNode\" singletontag=\"5\" verticalStretch=\"0\">"
  "    	 <property name=\"viewlabel\" action=\"default\">5</property>"
#  "      <property name=\"viewgroup\" action=\"default\">1</property>"
  "  	</view>"
  "   </item>"
  "   <item>"
  "    <view class=\"vtkMRMLSliceNode\" singletontag=\"Yellow+\">"
  "     <property name=\"orientation\" action=\"default\">Axial</property>"
  "     <property name=\"viewlabel\" action=\"default\">Y+</property>"
  "     <property name=\"viewcolor\" action=\"default\">#f6e9a2</property>"
#  "     <property name=\"viewgroup\" action=\"default\">1</property>"
  "    </view>"
  "   </item>"
  "  </layout>"
  " </item>"
  "</layout>")

customLayoutId=589

layoutManager = slicer.app.layoutManager()
layoutManager.layoutLogic().GetLayoutNode().AddLayoutDescription(customLayoutId, customLayout)                                         
layoutManager.setLayout(customLayoutId)